### ISSUE TITLE
Module is incompatible with knex versions >0.15.2

### ISSUE THREAD

**Issue by gmarkv10** [unexpectedjs/unexpected-knex#48]
I have the latest minor release of knex, 0.16.3 in my project, when I go to use this handy module is fails on a proxyrequire call, below is the first few lines of the stack:

```
Error: Cannot find module 'knex/lib/migrate'
    at Function.Module._resolveFilename (module.js:536:15)
    at Proxyquire._disableModuleCache (/Users/g/Documents/Projects/sso-sync-proto/node_modules/proxyquire/lib/proxyquire.js:273:19)
    at Proxyquire._disableCache (/Users/g/Documents/Projects/sso-sync-proto/node_modules/proxyquire/lib/proxyquire.js:241:15)
    at Proxyquire._withoutCache (/Users/g/Documents/Projects/sso-sync-proto/node_modules/proxyquire/lib/proxyquire.js:199:27)
    at Proxyquire.load (/Users/g/Documents/Projects/sso-sync-proto/node_modules/proxyquire/lib/proxyquire.js:129:15)
    at Object.<anonymous> (/Users/g/Documents/Projects/sso-sync-proto/node_modules/unexpected-knex/lib/unexpected-knex.js:26:30)
```
If I require knex @^0.15.2 things get off the ground fine but I would like to use the newest possible version. Any advice to configure to use the latest? Otherwise please resolve the bug.

**Comment by joelmukuthu** [comment]
Hi @gmarkv10. Yes, newer knex versions are currently not supported. The code needs to be updated to support custom migration sources (https://github.com/unexpectedjs/unexpected-knex/issues/27) and I haven't had time to look into that.

I currently don't have a lot of time to look into it but I'll try to look into it soon. If you have some time and would like to send a PR I can help you get started on that, would you be interested?

**Comment by joelmukuthu** [comment]
A fix for this is now released in v3
